export const signup = async (req, res) => {
  try {
    console.log('signup')
  } catch (error) {
    console.log(error)
  }
}

export const login = async (req, res) => {
  try {
    console.log('login')
  } catch (error) {
    console.log(error)
  }
}

export const logout = async (req, res) => {
  try {
    console.log('logout')
  } catch (error) {
    console.log(error)
  }
}
